export default [
  ['assim como', '~처럼'],
  ['assim que', '~하자마자'],
  ['através de', '~을 통하여'],
  ['cada vez mais', '점점 더'],
  ['caso', '~한 경우'],
  ['cerca de', '대략, 약'],
  ['claro', '물론'],
  ['com certeza', '확실히'],
  ['com relação a', '~에 관련하여'],
  ['como se', '마치 ~인 것처럼'],
  ['contanto que', '~하는 한'],
  ['da mesma maneira', '게다가'],
  ['daqui a pouco', '잠시 후에'],
  ['de braços abertos', '두 팔 벌려'],
  ['de fato', '사실, 실제로'],
  ['da forma que', '~하기 위해, ~하도록'],
  ['de graça', '무료로, 공짜로'],
  ['de jeito nenhum', '절대로 ~하지 않는다.'],
  ['de modo que', '그러므로'],
  ['de qualquero jeito', '어쨌든'],
  ['de repente', '갑자기; 어쩌면'],
  ['de sobra', '여분의'],
  ['de várias formas', '다양한 형태로'],
  ['de vez em quando', '가끔, 때때로'],
  ['desde que', '~하는 한; ~한 이래로'],
  ['diferentemente de', '~와 달리'],
  ['embora', '~에도 불구하고'],
  ['em breve', '조만간, 곧'],
  ['em cima da hora', '마지막 순간에, 임박해서'],
  ['em geral', '일반적으로'],
  ['em outras palavras', '바꿔 말하면'],
  ['em perigo', '위험에 직면해서'],
  ['em primeiro lugar', '먼저, 첫째로'],
  ['em relação a', '~에 관련하여'],
  ['em seguida', '곧바로, 곧이어'],
  ['em termos de', '~에 의하여, ~의 점에서'],
  ['em todas as partes', '어디서든, 어디에서나'],
  ['em torno de', '대략, 약'],
  ['em vão', '헛되이'],
  ['em vez de', '~대신에'],
  ['enfim', '어쨌든'],
  ['enquanto', '~하는 동안'],
  ['enquanto que', '그 동안, 한편'],
  ['esteja onde estiver', '어디에 있더라도'],
  ['fora de ordem', '순서가 뒤바뀌어'],
  ['fora do alcance', '손이(힘이) 닿지 않는'],
  ['haja o que houver', '무슨 일이 있어도'],
  ['independentemente de', '~에 관계없이'],
  ['infelizmente', '불행히도'],
  ['isso é', '즉, 말하자면'],
  ['já que', '~이므로, ~한 이상'],
  ['logo depois', '바로 다음에'],
  ['logo que', '일단 ~하면, ~하자마자'],
  ['na época', '그 때는'],
  ['na hora', '곧바로'],
  ['na prática', '실제로'],
  ['na verdade', '사실은'],
  ['na volta', '돌아오는 길에'],
  ['naquela época', '그 당시에는'],
  ['nem um pouco', '조금도, 전혀'],
  ['nesse caso', '그럴 경우'],
  ['no começo', '처음에'],
  ['no entanto', '그러나, 하지만'],
  ['no fim', '마침내, 마지막에는'],
  ['no fim das contas', '결국, 최후에는'],
  ['no fundo', '본심은, 마음 속으로는'],
  ['no início', '처음에는, 최초에는'],
  ['no meio de', '~의 중앙에'],
  ['nos mais dia menos dia', '조만간'],
  ['ou seja', '즉, 바꿔 말하면'],
  ['pelo contrário', '그와는 반대로, 오히려'],
  ['pelo jeito', '보기에, 외관상으로는'],
  ['pelo menos', '적어도'],
  ['por causa de', '~때문에'],
  ['por coincidência', '우연의 일치로'],
  ['por engano', '실수로'],
  ['por enquanto', '당분간, 현재로는'],
  ['por exemplo', '예를 들면'],
  ['por falar em', '~에 관해서 말하자면'],
  ['por isso', '그래서'],
  ['por mais que', '아무리 많이 ~하더라고'],
  ['por meio e', '~을 거쳐서, ~에 의하여'],
  ['por mim', '나로서는'],
  ['por nada', '그냥, 아무 이유 없이'],
  ['por outro lado', '다른 한편으로는, 반면에'],
  ['por sua vez', '다른 한편으로는, 반면에'],
  ['por várias vezes', '여러 번, 되풀이해서'],
  ['quando você quiser', '네가 원할 때 언제든지'],
  ['quantas vezes quiser', '네가 원하면 몇 번이든지'],
  ['quanto antes', '가능한 빨리'],
  ['quanto mais', '더 ~할수록'],
  ['quanto menos', '덜 ~할수록'],
  ['quanto você quiser', '네가 원하는 양만큼 얼마든지'],
  ['quantos você quiser', '네가 원하는 수만큼 얼마든지'],
  ['quem você quiser', '원하는 사람이면 누구든'],
  ['se por acaso', '혹시'],
  ['se preferir', '(그걸 더) 원하면, 선호하면'],
  ['se quiser', '원하면, 그렇게 하고 싶으면'],
  ['segundo', '~에 의하면, ~에 따르면'],
  ['seja quem for', '누구든지, 누구라도'],
  ['sem comentários', '노코멘트'],
  ['sem compromisso', '약속 없이, 의무감 없이'],
  ['sem dúvida', '확실히, 의심할 여지없이'],
  ['sem estresse', '스트레스 없는'],
  ['sem exceção', '예외 없이'],
  ['sem problema', '문제 없이'],
  ['sempre que', '~할 때마다'],
  ['sob controle', '통제하에'],
  ['tal como', '~와 같은'],
  ['um monte de', '엄청 많은'],
  ['um pouco de', '조금'],
  ['uma vez que', '한번(일단) ~하면'],
  ['chega de', '더 이상 ~하지 않다. 이제 그만!'],
  ['como assim?', '무슨 뜻이지?'],
  ['dá um tempo', '시간을 좀 줘! 너무 그러지 마!'],
  ['e aí?', '(만났을 때) 안녕; 그래서'],
  ['e daí?', '그래서 뭐? 그게 어쨌다는 거야?'],
  ['então tá', '(좋아, 알았어) 그럼'],
  ['fuque com Deus', '(신의) 축복 있기를!'],
  ['graças a Deus', '신의 은총 덕분에, 고맙게도'],
  ['isso mesmo', '바로 그거야!'],
  ['juízo', '(어머니가 아이에게) 다녀와!, 얌전히 있어!'],
  ['nossa!', '야!, 와!'],
  ['olha só', '이것 봐라, 흥미로운데'],
  ['pelo amor de Deus', '제발!'],
  ['pois é', '그러게'],
  ['pois não', '물론이죠; 무얼 도와드릴까요?'],
  ['que barato', '아주 싸!'],
  ['que caro', '아주 비싸!'],
  ['que bom que', '~해서 아주 좋다.'],
  ['que bom!', '좋았어! 잘됐어!'],
  ['que chato!', '지겨워! 지루해!; 짜증나! 귀찮아!'],
  ['que coisa!', '이런! 뭐야!'],
  ['que demora!', '너무 오래 걸려!'],
  ['que emoção!', '감동이야! 흥분돼!'],
  ['que engraçado!', '우스워! 웃겨!'],
  ['que estranho!', '이상해!'],
  ['que foi', '무슨 일이야?'],
  ['que gracinha!', '귀여워!'],
  ['que inveja!', '질투나!'],
  ['que legal!', '좋았어! 잘됐어!'],
  ['que pena!', '안됐어! 유감이야!'],
  ['que sacanagem!', '못된 짓이야! 나빠!'],
  ['que saudades!', '그리워!'],
  ['que sorte!', '행운이야! 다행이야!'],
  ['que vergonha!', '창피해! 난처해!'],
  ['se Deus quiser', '신이(사정이) 허락한다면'],
  ['tá bom?, tá legal?', '알았지? 괜찮지? 좋지?'],
  ['tanto faz', '아무래도 좋다. 아무 상관없다.'],
  ['tapo o quê?', '어떤 건데?'],
  ['tudo bom', '좋아.'],
  ['você acha?', '그렇게 생각해?'],
  ['você que sabe', '선택은 네게 달렸어. 네 맘대로 해']
]
